<?php
namespace GoBlocks\Blocks;

defined( 'ABSPATH' ) || exit;

/**
 * Box block — PHP render callback.
 *
 * All styles are pre-generated by the TypeScript CssEngine and stored in
 * `attributes.generatedCss`. PHP only outputs the wrapper element with the
 * correct classes, attributes, and inner block content.
 */
class Box extends BlockBase {

	/**
	 * Block name (without namespace prefix).
	 *
	 * @return string
	 */
	public function get_name(): string {
		return 'box';
	}

	/**
	 * Render the Box block.
	 *
	 * @param array<string, mixed> $attributes Block attributes.
	 * @param string               $content    Inner blocks HTML.
	 * @param \WP_Block            $block      Block instance.
	 * @return string Rendered HTML.
	 */
	public function render( array $attributes, string $content, \WP_Block $block ): string {
		$unique_id = $this->get_unique_id( $attributes );

		if ( ! $unique_id ) {
			return $content;
		}

		$tag_name       = $this->get_tag_name( $attributes, 'div' );
		$block_class    = $this->get_block_class( $unique_id );          // e.g. gb-box-a1b2c3
		$global_classes = $this->get_global_classes( $attributes );

		$animation_class = sanitize_html_class( (string) ( $attributes['animationClass'] ?? '' ) );
		$extra           = array_values( array_filter( array( 'gb-box', $animation_class ) ) );

		// build_class_string returns an already-escaped string.
		$classes = $this->build_class_string( $block_class, $global_classes, $extra );

		// build_html_attrs expects a key→value map, not the full attributes array.
		$html_attrs = $this->build_html_attrs( $this->get_html_attributes( $attributes ) );

		// Link mode (tagName = a).
		if ( 'a' === $tag_name ) {
			$html_attrs .= $this->build_link_attrs( $attributes );
		}

		// ARIA label.
		$aria_label = sanitize_text_field( (string) ( $attributes['ariaLabel'] ?? '' ) );
		if ( $aria_label ) {
			$html_attrs .= ' aria-label="' . esc_attr( $aria_label ) . '"';
		}

		return sprintf(
			'<%1$s class="%2$s"%3$s>%4$s</%1$s>',
			esc_attr( $tag_name ),
			$classes,       // already escaped by build_class_string
			$html_attrs,    // already escaped, has leading space
			$content
		);
	}

	/**
	 * Build href/target/rel attribute string for link mode.
	 *
	 * @param array<string, mixed> $attributes Block attributes.
	 * @return string Attribute fragment with leading space.
	 */
	private function build_link_attrs( array $attributes ): string {
		$link   = esc_url( (string) ( $attributes['link'] ?? '' ) );
		$target = (string) ( $attributes['linkTarget'] ?? '_self' );
		$rel    = sanitize_text_field( (string) ( $attributes['linkRel'] ?? '' ) );

		// Only allow safe target values.
		if ( ! in_array( $target, array( '_self', '_blank' ), true ) ) {
			$target = '_self';
		}

		// Always add noopener noreferrer for new-tab links.
		if ( '_blank' === $target ) {
			$rel_parts = array_unique(
				array_filter(
					array_merge( array( 'noopener', 'noreferrer' ), explode( ' ', $rel ) )
				)
			);
			$rel       = implode( ' ', $rel_parts );
		}

		$attrs = '';

		if ( $link ) {
			$attrs .= ' href="' . $link . '"';
		}

		$attrs .= ' target="' . esc_attr( $target ) . '"';

		if ( $rel ) {
			$attrs .= ' rel="' . esc_attr( $rel ) . '"';
		}

		return $attrs;
	}
}

// Self-register into the block class list.
add_filter(
	'goblocks_block_classes',
	static function ( array $classes ): array {
		$classes[] = Box::class;
		return $classes;
	}
);
